### ISSUE TITLE
VS Code extension created a strange race condition on my machine

### ISSUE THREAD

**Issue by pdhoward** [microclimate-dev2ops/microclimate-vscode-tools#24]
1. installed the microclimate app on my windows 10 machine
2. checkout with docker works 
3. created first nodejs project, following tutorial
4. installed mc extenion on vscode v 1.30.2
5. right clicked on view per docs and selected new connection (9090 default)

A very odd 'shadowy race condition' was triggered ... with a flickering ui in my editor ... evidently attempting to make a connections, unable to do it ... but never timing out. I uninstalled the extenion -- but am hoping you can either give me a more complete set of instructions on what I need to do ... or other direction so I can help you isolate this issue   ... I am new to microclimate but our company is hunting for a microservices solution and are currently testi

Here is screen shot ... not sure if you can see the faint flickering

![image](https://user-images.githubusercontent.com/7431751/51556427-293f3e80-1e48-11e9-96e5-1a004b8e453c.png)

**Comment by tetchel** [comment]
I am able to reproduce this on a Windows machine. Will fix ASAP.

**Comment by tetchel** [comment]
Fixed in master

**Comment by tetchel** [comment]
Fixed in 19.1.1
