### ISSUE TITLE
A popup is displayed every time VSCode is opened when Microclimate is not running

### ISSUE THREAD

**Issue by rajivnathan** [microclimate-dev2ops/microclimate-vscode-tools#28]
**Environment:**
- Extension version (eg. `19.2.0`): 19.3
- Microclimate version (eg. `19.02`): 19.02
- [VS Code version](https://code.visualstudio.com/docs/supporting/faq#_how-do-i-find-the-vs-code-version) (eg. `1.32.1`): 1.32.3
 - OS: MacOS Mojave

**Describe the bug:**
Screenshots are recommended if applicable.
![image](https://user-images.githubusercontent.com/20015929/54927308-4e076f00-4ee8-11e9-8a9e-137024186b73.png)

**To Reproduce:**
Please provide detailed steps.
Start VSCode without Microclimate running.

**Comment by tetchel** [comment]
Seems a lot of people don't like this behaviour.
It has been fixed in the ICP branch. I'll try to pull out that change to get it into the next release if there is another release before I merge ICP support.
